---
- name: reload systemd for podman user
  # Only reload daemon
  ansible.builtin.command: machinectl shell {{ podman_user_name }}@.host /usr/bin/systemctl --user daemon-reload

- name: restart rootless podman
  ansible.builtin.command: machinectl shell {{ podman_user_name }}@.host /usr/bin/systemctl --user restart podman.socket

- name: migrate podman containers
  ansible.builtin.command: podman system migrate
