---
- name: reload systemd
  # Only reload daemon, use command module since systemd module doesn't support this
  ansible.builtin.command: systemctl daemon-reload  # noqa command-instead-of-module

- name: restart rootless podman
  ansible.builtin.command: machinectl shell {{ podman_user_name }}@.host /usr/bin/systemctl --user restart podman.socket

- name: migrate podman containers
  ansible.builtin.command: podman system migrate
